import { Header } from '@/components/layout/Header'
import { FinalCTA } from '@/components/sections/FinalCTA'

export function PrivacyPolicy() {
    return (
        <div className="relative min-h-screen bg-bg-primary text-text-primary flex flex-col">
            <Header />
            <main className="flex-1 w-full pt-32 pb-24">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 mt-12">
                    <div className="prose prose-invert prose-blue max-w-none text-text-secondary prose-headings:text-text-primary prose-a:text-accent-primary">
                        <h1 className="text-4xl md:text-5xl font-medium tracking-tight mb-12">Privacy Policy</h1>
                        <p className="text-lg">Flow is an open-source project that respects your privacy. We believe that your data belongs to you.</p>
                        
                        <h2 className="text-2xl font-semibold mt-12 mb-4">Data Collection</h2>
                        <p>Flow does not collect, transmit, or sell any personal information. All data generated by your usage, including your watch history, search history, and algorithmic recommendations (via the FlowNeuro Engine), is stored locally on your device.</p>
                        
                        <h2 className="text-2xl font-semibold mt-12 mb-4">External Services</h2>
                        <p>To provide video and music content, Flow communicates directly with YouTube's servers. These requests are made from your IP address, and YouTube may log this activity according to their own Privacy Policy. We do not use any intermediary servers to proxy this traffic, ensuring that we never see your data.</p>
                        
                        <h2 className="text-2xl font-semibold mt-12 mb-4">Third-Party Integrations</h2>
                        <ul>
                            <li><strong>SponsorBlock:</strong> Flow uses SponsorBlock to skip sponsored segments. This involves sending anonymous, hashed video IDs to the SponsorBlock API.</li>
                            <li><strong>Return YouTube Dislike:</strong> Flow fetches dislike statistics from the Return YouTube Dislike API.</li>
                            <li><strong>DeArrow:</strong> Flow may fetch alternative titles and thumbnails from the DeArrow API.</li>
                        </ul>
                        <p>You can disable any of these integrations in the app settings if you prefer not to use them.</p>

                        <h2 className="text-2xl font-semibold mt-12 mb-4">Telemetry & Crash Reporting</h2>
                        <p>Flow contains zero analytics, tracking, or crash reporting SDKs. We have no way of knowing how you use the app or if it crashes on your device. If you encounter a bug, you must manually report it on our GitHub Issues page.</p>

                        <h2 className="text-2xl font-semibold mt-12 mb-4">Contact</h2>
                        <p>If you have any questions about this Privacy Policy, please reach out via our <a href="https://github.com/A-EDev/Flow" target="_blank" rel="noopener noreferrer">GitHub repository</a> or the official <a href="https://reddit.com/r/flow_official" target="_blank" rel="noopener noreferrer">subreddit</a>.</p>
                    </div>
                </div>
            </main>
            <FinalCTA />
        </div>
    )
}
export default PrivacyPolicy
